name: Cowsay CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
    run-dragon-script:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Repository
            uses: actions/checkout@v3

          - name: Install Cowsay
            run: |
             if ! command -v cowsay &> /dev/null
             then
                echo "cowsay could not be found, installing..."
                sudo apt-get update && sudo apt-get install -y cowsay
             else
                echo "cowsay is already installed."
                fi

          - name: Run dragon.sh script
            run: |
              chmod +x ./dragon.sh
              ./dragon.sh